version: 0.2

env:
  variables:
    NODE_OPTIONS: --openssl-legacy-provider

phases:
  install:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://my-react-app-chat --delete

artifacts:
  files:
    - '**/*'
